### ISSUE TITLE
报错；SSL的问题

### ISSUE THREAD

**Issue by Ramon403** [ShenXuGongZi/FanHaoSearch#6]
Traceback (most recent call last):
  File "FanHao_win.py", line 61, in <module>
  File "urllib2.pyc", line 127, in urlopen
  File "urllib2.pyc", line 404, in open
  File "urllib2.pyc", line 422, in _open
  File "urllib2.pyc", line 382, in _call_chain
  File "urllib2.pyc", line 1222, in https_open
  File "urllib2.pyc", line 1184, in do_open
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>

**Comment by onion83** [comment]
+1

**Comment by ShenXuGongZi** [comment]
这个坑好久没来了。。 urllib2 会有这个问题我最近解决
